// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Volue.ForecastService.Repositories;

#nullable disable

namespace Volue.ForecastService.Repositories.Migrations
{
    [DbContext(typeof(ForecastDbContext))]
    partial class ForecastDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Volue.ForecastService.Repositories.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("companies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Energy Trading Corp",
                            UpdatedAt = new DateTime(2026, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Volue.ForecastService.Repositories.Entities.Forecast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("HourUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("hour_utc");

                    b.Property<decimal>("Mwh")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("mwh");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HourUtc")
                        .HasDatabaseName("idx_forecasts_hour");

                    b.HasIndex("PlantId", "HourUtc")
                        .IsUnique()
                        .HasDatabaseName("idx_forecasts_plant_hour");

                    b.ToTable("forecasts", (string)null);
                });

            modelBuilder.Entity("Volue.ForecastService.Repositories.Entities.PowerPlant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CapacityMwh")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("capacity_mwh");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("power_plants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CapacityMwh = 150.0000m,
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Country = "Turkey",
                            CreatedAt = new DateTime(2026, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Istanbul Wind Farm",
                            UpdatedAt = new DateTime(2026, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CapacityMwh = 200.0000m,
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Country = "Bulgaria",
                            CreatedAt = new DateTime(2026, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Sofia Solar Park",
                            UpdatedAt = new DateTime(2026, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CapacityMwh = 300.0000m,
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Country = "Spain",
                            CreatedAt = new DateTime(2026, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Madrid Hydro Station",
                            UpdatedAt = new DateTime(2026, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Volue.ForecastService.Repositories.Entities.Forecast", b =>
                {
                    b.HasOne("Volue.ForecastService.Repositories.Entities.PowerPlant", "Plant")
                        .WithMany("Forecasts")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Volue.ForecastService.Repositories.Entities.PowerPlant", b =>
                {
                    b.HasOne("Volue.ForecastService.Repositories.Entities.Company", "Company")
                        .WithMany("PowerPlants")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Volue.ForecastService.Repositories.Entities.Company", b =>
                {
                    b.Navigation("PowerPlants");
                });

            modelBuilder.Entity("Volue.ForecastService.Repositories.Entities.PowerPlant", b =>
                {
                    b.Navigation("Forecasts");
                });
#pragma warning restore 612, 618
        }
    }
}
